version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing Python
          command: 'apt-get update && apt-get install python'
      - run:
          name: Installing PERL
          command: 'apt-get update && apt-get install perl'
      - run:
          name: Installing NASM
          command: 'apt-get update && apt-get install nasm'
      - run:
          name: Installing Vulkan SDK
          command: 'apt-get update && apt-get install libvulkan-dev'
      - run:
          name: Installing CUDA
          command: 'apt-get update && apt-get install nvidia-cuda-toolkit'
      - run:
          name: Installing Optix
          command: 'apt-get update && apt-get install libnvoptix1'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
